### ISSUE TITLE
Installed using Docker Image, "Create Instance" returns 404

### ISSUE THREAD

**Issue by IzMichael** [Lodestone-Team/client#132]
# Description
I installed Lodestone Core using the docker image on my Ubuntu server, and I'm able to connect to the core from the desktop app
![image](https://user-images.githubusercontent.com/57115702/225865682-b60d98df-1793-4cfe-b251-198ab3ea59d5.png)

But when I try to click "Create a new Instance", it just sits on the loading screen, and a quick peek in the devtools just shows that it's not finding the API endpoint.
![image](https://user-images.githubusercontent.com/57115702/226147256-e48dc0e1-86bf-4806-8e4e-c95b62098b34.png)

Have I configured some network settings wrong? All I've done was install the docker image and allow port `16662` past my UFW firewall.

**Comment by CheatCod** [comment]
This is a very weird error, works fine on my machine with a local core (no docker) and the webapp 
![image](https://user-images.githubusercontent.com/47200772/225930506-e26001b3-8f90-409a-9fb2-e12b4b313d8a.png)

The 404 implies the endpoint doesn't exist, which doesn't make any sense. The only possible explanation I can think of is that you are somehow using 0.4.2 core with 0.4.3 dashboard, in that case there will be an warning

**Comment by IzMichael** [comment]
You've sent a screenshot of your `OPTIONS`request, which **did** return 200 for me. Does the `GET` request also return 200 for you?

**Comment by CheatCod** [comment]
I'm not sure why there is an `OPTIONS` request, but all the `GET` requests return 200 for me
![image](https://user-images.githubusercontent.com/47200772/226074265-c738ff1d-19f9-4c48-836b-786013db9b93.png)

**Comment by pinnouse** [comment]
Sorry, built Docker image from wrong branch. I've rebuilt the multiarch images, so please try repulling the images.

**Comment by modscleo4** [comment]
Edit you first image, your VPS IP is not blurred under `Remote Address`

**Comment by IzMichael** [comment]
> Edit you first image, your VPS IP is not blurred under `Remote Address`

Ack! Ty

**Comment by IzMichael** [comment]
> Sorry, built Docker image from wrong branch. I've rebuilt the multiarch images, so please try repulling the images.

Yep! That's fixed it. Thanks!
