### ISSUE TITLE
Subprocess is "detached" when a non utf-8 character is emitted by it

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/client#144]
# Description

If a subprocess managed by lodestone emits a non utf-8 character, an attempt to read will fail and lodestone will assume the process has existed while the process is still running.

# Steps to reproduce (optional)

**Comment by CheatCod** [comment]
Fixed in https://github.com/Lodestone-Team/lodestone_core/commit/d6aaf4c2c4e24af9feca63f59f24bc31660be2eb

**Comment by phant0m2290** [comment]
it seems to only happen with already created instances. when i start a newly created instance it wont detach and works fine. and for some reason with only that instance it seems to be fixed. even when i restart the core. but not for the others.
