### ISSUE TITLE
Setup CORS for Axum

### ISSUE THREAD

**Issue by CheatCod** [Lodestone-Team/client#48]
# Intention:

Rocket has problems with CORS policy which need to be explicitly addressed.

Look into if Axum needs to be set up to avoid such issue, if so fix it.

# Why is it necessary:

CORS broke the Rocket app before.

**Comment by Ynng** [comment]
Done, added cors via tower_http middleware in commit https://github.com/Lodestone-Team/client/commit/5069c4fabb1a9dbd7f418cd9b0abdec3a4047947
