### ISSUE TITLE
New global setting "host name"

### ISSUE THREAD

**Issue by Ynng** [Lodestone-Team/client#80]
# Intention:

- [x] Add a new global setting "hostname"
- [ ] Have it default to localhost for now? (maybe we can default to the user's public ip once we got that figured out)
- [x] Add an endpoint for getting and setting this value

# Why is it necessary:

Example of issue:
A user setup a new Lodestone Core and connects to it through `localhost:16662`, then creates a Minecraft server.
When they try to copy the server's IP to share with their friend, they get `localhost:25565`.

Example of issue:
A user sets up a custom domain `myserver.com` pointing to their server at `123.123.123.123` running Lodestone Core and Minecraft. But the dashboard keeps displaying `123.123.123.123`

**Comment by CheatCod** [comment]
Done
